Service wbs Comment API
Bledhard/GreenShop pull request #60
Opened 2019-03-09 13:17 UTC by alexars

Added API calls methods for Comment API.
Covered them with unit test.

2019-03-09 13:47 UTC, dreytko requested changes
I've found some major issues I would like you to change before we can merge the pull request.
Reach me out if you need any kind of guidance or assistance.

2019-03-09 13:47 UTC, Bledhard commented on src/api/Web.Bff.Shopping/Config/CommentApiOperations.cs
> +            public static string AddComment() => $"/api/comments/";
This string has no reason to be a method type.
- [ ] replace with ``` public static string AddComment = $"/api/comments/";```

2019-03-09 13:47 UTC, Bledhard commented on src/api/Web.Bff.Shopping/Config/CommentApiOperations.cs
> +            public static string GetAllPruductComments(int productId) => $"/api/comments/product/{productId}";
Fix typo

2019-03-09 13:47 UTC, Bledhard commented on src/api/Web.Bff.Shopping/Config/ProductApiOperations.cs
> +
Next time, try to avoid changes like these in files - they're littering the file history, making its harder to find something specific.

2019-03-09 13:47 UTC, Bledhard commented on src/api/Web.Bff.Shopping/Services/Catalog/Consumers/CommentConsumer.cs
> +        private async Task<IRestResponse<T>> ExecuteAsync<T>(RestRequest request) where T : new()
We should remove this method once #55 is merged.

2019-03-09 13:47 UTC, Bledhard commented on src/api/Web.Bff.Shopping/Config/CommentApiOperations.cs
> +            public static string AddComment() => $"/api/comments/";
Also, did you test it? When I was making the similar task with Products, I've removed these starting slashes, as I was always adding the URL to the appsettings.json with the slash in the end, so requests had the wrong URL when baseUrl and resource are concatenated.

2019-03-09 13:47 UTC, Bledhard commented on src/api/Web.Bff.Shopping/appsettings.json
> +    "catalog": "https://localhost:44391"
This should be definitely undone. The reason for it is that we are having our appsettings.json just as an example, so adding a proper URL even for local testing is a bad habit. The only changes that should be made in appsettings.json - example update when config was restructured.
- [ ] remove changes made in appsettings.json

Also, for the sake of consistency, I would like to ask you to add ending slash in your appsettings.development.json and also remove starting slash on CommentsApiOperation strings.

2019-03-09 13:47 UTC, Bledhard commented on tests/UnitTests/Catalog/Services/CommentsRepository/AddCommentTests.cs
> +        //TODO: Repair
This comment is alarming me: what should be repaired? Either remove the comment or make necessary changes and remove comment as well.

2019-03-09 13:47 UTC, Bledhard commented on tests/UnitTests/Catalog/Services/CommentsRepository/AddCommentTests.cs
> +            //Assert.IsInstanceOfType(result.Exception.InnerException, typeof(ValidationException));
Remove the commented code

2019-03-10 18:27 UTC, alexars commented
I've made all the changes according to your remarks.

2019-03-10 19:26 UTC, Bledhard commented
@alexars I see no commits after the review. Maybe, you forgot to push changes to the remote?

2019-03-10 20:04 UTC, dreytko requested changes
You've lost one small thing here. Everything else looks fine for me.

2019-03-10 20:04 UTC, Bledhard commented on src/api/Web.Bff.Shopping/Config/CommentApiOperations.cs
> +            public static string GetAllPruductComments(int productId) => $"api/comments/product/{productId}";
GetAllPruductComments - fix typo

2019-03-10 20:11 UTC, dreytko approved these changes

2019-03-10 20:14 UTC, merged